### PR TITLE
AYr-900/updated label in browse-consignment.html

### PR DESCRIPTION
**Pull request by pgandhizaizi**
### After

- [ ] Requires env variable(s) to be updated

### CODE REVIEW

**Comment by pgandhizaizi** [comment]
sorry, the changes are as follows
amended browse-consignment.html to replace label 'Dates' to 'Record dates' in filter panel

**Comment by pgandhizaizi** [comment]
before
image
image


after

**Review by colinbowen — DISMISSED** [review]
Looks good, reviewed on call.

**Review by colinbowen — APPROVED** [review]
Looks ok, snapshots updated

**Pull request merged**
