### PR TITLE
AYR-758/browse view design changes

### PR DESCRIPTION
**Pull request by pgandhizaizi**
## Changes in this PR

1. set correct table header values for browse views (all, transferring body, series, consignment)
2. set correct alignment for table headers
3. added missing sorting orders for browse view (AAU users)

## JIRA ticket

AYR-758

### After

- [ ] Requires env variable(s) to be updated

### CODE REVIEW

**Comment by anthonyhashemi** [comment]
can you add before and after pictures of the intended changes?

**Comment by pgandhizaizi** [comment]
browse all view - aau users
before
image
after
image
browse-all view -sorting options
before
image
after
image

browse transferring body view
before
image

after
image

browse series view
before
image

after
image

browse consignment view
before
image

after
image

**Comment by pgandhizaizi** [comment]
before and after changes screen shots added

**Comment by pgandhizaizi** [comment]
_search_results_summary.scss has a class which affects the other views last-child , so amended the class to specifically work for search-results-summary template

**Review by anthonyhashemi — APPROVED** [review]

**Pull request merged**
