### PR TITLE
AYR-965 - Modify Browse and Record pages tab order to be consistent with Search page

### PR DESCRIPTION
**Pull request by ltrasca**
## Changes in this PR

- changed the order of the browser and record pages HTML elements to include pagination right after table
- because of this change, styles and tabbing order across browse and search pages should now be consistent

*Why element order change and not tabIndex to change tabbing order?*

Using tabIndex to dictate the order of keyboard tabbing would make future development more tedious and harder to maintain, changing the order of elements should be a more organic approach that ensures future consistency

## JIRA ticket

AYR-965 -> https://national-archives.atlassian.net/browse/AYR-965

### Before

image

### After

image

### Comparison to Search page

image

- [ ] Requires env variable(s) to be updated

### CODE REVIEW

**Review by anthonyhashemi — COMMENTED** [review]
I noticed that the design changed slightly, specifically spacing between the pagination widget and the table. Worth checking with @Terry-Price

**Comment by ltrasca** [comment]
> I noticed that the design changed slightly, specifically spacing between the pagination widget and the table. Worth checking with @Terry-Price

@anthonyhashemi I've passed the changes by Terry and he expressed his approval, I've also added the screenshots to the Jira ticket so he can have a 2nd look - he mentioned he didn't have access to the GitHub PR

**Review by anthonyhashemi — DISMISSED** [review]
Approving assuming Terry is happy with the change in pagination widget spacing

**Comment by pgandhizaizi** [comment]
Please update the visual snapshots for all browsers (firefox, webkit , chromium) using the playwright command
pytest e2e_tests/test_visual_regression.py --base-url=https://localhost:5000 --browse firefox --update snapshots 
option to make sure all visual regression tests passed

**Pull request closed without merging**
