### PR TITLE
AYR-929/browse consignment view content changes

### PR DESCRIPTION
**Pull request by pgandhizaizi**
## Changes in this PR
1. content changes on browse-consignment.html
2. updated test cases in test_browse_consignment.py 
3. update end to end test cases in e2e_tests/test_browse_consignment.py

## JIRA ticket

AYR - 929

### Before
image

### After
image

- [ ] Requires env variable(s) to be updated

### CODE REVIEW

**Comment by pgandhizaizi** [comment]
perform full unit testing
image


performed full end to end tests for browse consignment view
image

**Comment by pgandhizaizi** [comment]
executed tests against each browser 
image

**Review by colinbowen — APPROVED** [review]
Changes ok, possible to update the xls to mark changes made.

**Comment by colinbowen** [comment]
Also the visual regression snapshots will need updating

**Pull request merged**
