### PR TITLE
Configure flask app logger and detail in readme for devs

### PR DESCRIPTION
**Pull request by anthonyhashemi**
## Changes in this PR

- Configure flask app logger and detail in readme for devs

## JIRA ticket

https://national-archives.atlassian.net/jira/software/projects/AYR/boards/66?assignee=63b4326678aabbefa9d4400d&selectedIssue=AYR-502

Have verified that the logs come out as expected locally and when running on AWS lambda they come through as expected in cloudwatch logs.

### CODE REVIEW

**Review by pgandhizaizi — COMMENTED** [review]
do we need to configure conftest.py for mocking the logging object ?

**Comment by anthonyhashemi** [comment]
> do we need to configure conftest.py for mocking the logging object ?

Spoken offline, can just use pytests inbuilt fixture, caplog. Will add a line about this

**Comment by anthonyhashemi** [comment]
> > do we need to configure conftest.py for mocking the logging object ?
> 
> Spoken offline, can just use pytests inbuilt fixture, caplog. Will add a line about this

Done

**Review by pgandhizaizi — APPROVED** [review]
looks good , approved

**Pull request merged**
